clc;
clear all;
close all;
I = im2double(imread('cameraman.tif'));
subplot(2,2,1),imshow(I),title('Input Image');
LEN = 21;
THETA = 11;
PSF = fspecial('motion', LEN, THETA);
blurred = imfilter(I, PSF, 'conv', 'circular');
noise_mean = 0;
noise_var = 0.0001;
blurred_noisy = imnoise(blurred, 'gaussian', noise_mean, noise_var);
subplot(2,2,2),imshow(blurred_noisy),title('Input Image degraded by motion blur and noise');
estimated_nsr = 0;
wnr2 = deconvwnr(blurred_noisy, PSF, estimated_nsr);
subplot(2,2,3), imshow(wnr2),title('Restoration of Blurred, Noisy Image Using Ideal Inverse Filter');
estimated_nsr = noise_var / var(I(:));
wnr3 = deconvwnr(blurred_noisy, PSF, estimated_nsr);
subplot(2,2,4),imshow(wnr3), title('Restoration of Blurred, Noisy Image Using Estimated NSR');
